// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC18t6sNkWO-pwM4mc1XD5-oS2Btg7wmqw',
    appId: '1:70165945558:web:2248eb75ffe529eef1bd77',
    messagingSenderId: '70165945558',
    projectId: 'goalpulse-38583',
    authDomain: 'goalpulse-38583.firebaseapp.com',
    storageBucket: 'goalpulse-38583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqfpDdBXab9niR2jmcaQo_ja_TegkggA',
    appId: '1:70165945558:android:a31bd1a36a482ecef1bd77',
    messagingSenderId: '70165945558',
    projectId: 'goalpulse-38583',
    storageBucket: 'goalpulse-38583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHYR6SI4F-Pj3h9drmmB8TnHPOvN-oRE',
    appId: '1:70165945558:ios:b2bbb387728caabff1bd77',
    messagingSenderId: '70165945558',
    projectId: 'goalpulse-38583',
    storageBucket: 'goalpulse-38583.firebasestorage.app',
    iosBundleId: 'com.example.goalpulse',
  );
}
